<a href="https://colab.research.google.com/github/jiakhelal/medication-recommendation-system-/blob/main/medication_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd


In [11]:
df = pd.read_csv(
    "/content/Training.csv",
    engine="python",
    on_bad_lines="skip"
)

multi-class-classification problem


In [12]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [13]:
df.shape

(4920, 133)

In [14]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [15]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [114]:
len(df['prognosis'].unique())

41

train and spilt dataset

In [115]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [116]:
x=df.drop("prognosis",axis=1)

In [117]:
y=df["prognosis"]

In [118]:
print("Number of features:", x.shape[1])

Number of features: 132


In [119]:
le=LabelEncoder()
le.fit(y)
y=le.transform(y)

In [120]:
y

array([15, 15, 15, ..., 38, 35, 27])

In [25]:
x

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [121]:
import pickle

symptoms_list = x.columns.tolist()

with open("models/symptoms_list.pkl", "wb") as f:
    pickle.dump(symptoms_list, f)

print("Saved symptoms:", len(symptoms_list))  # MUST be 132


Saved symptoms: 132


In [111]:
disease_dict = {i: disease for i, disease in enumerate(le.classes_)}

with open("models/disease_dict.pkl", "wb") as f:
    pickle.dump(disease_dict, f)

print(disease_dict)


{0: '(vertigo) Paroymsal  Positional Vertigo', 1: 'AIDS', 2: 'Acne', 3: 'Alcoholic hepatitis', 4: 'Allergy', 5: 'Arthritis', 6: 'Bronchial Asthma', 7: 'Cervical spondylosis', 8: 'Chicken pox', 9: 'Chronic cholestasis', 10: 'Common Cold', 11: 'Dengue', 12: 'Diabetes ', 13: 'Dimorphic hemmorhoids(piles)', 14: 'Drug Reaction', 15: 'Fungal infection', 16: 'GERD', 17: 'Gastroenteritis', 18: 'Heart attack', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 23: 'Hypertension ', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 26: 'Hypothyroidism', 27: 'Impetigo', 28: 'Jaundice', 29: 'Malaria', 30: 'Migraine', 31: 'Osteoarthristis', 32: 'Paralysis (brain hemorrhage)', 33: 'Peptic ulcer diseae', 34: 'Pneumonia', 35: 'Psoriasis', 36: 'Tuberculosis', 37: 'Typhoid', 38: 'Urinary tract infection', 39: 'Varicose veins', 40: 'hepatitis A'}


In [32]:
x = pd.DataFrame(x)
y = pd.Series(y)


In [33]:
x_np = x.values  # DataFrame → NumPy

rng = np.random.default_rng(42)

# choose noise strength (0.15 recommended)
noise = rng.binomial(1, 0.20, size=x_np.shape)

x_noisy = np.clip(x_np + noise, 0, 1)

x = x_noisy



In [34]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)



In [125]:
disease_merge_map = {
    "Hepatitis A": "Hepatitis",
    "Hepatitis B": "Hepatitis",
    "Hepatitis C": "Hepatitis",
    "Hepatitis D": "Hepatitis",
    "Hepatitis E": "Hepatitis",

    "Arthritis": "Joint Disorder",
    "Osteoarthristis": "Joint Disorder",

    "(vertigo) Paroymsal  Positional Vertigo": "Vertigo",

    "Bronchial Asthma": "Respiratory Disease",
    "Common Cold": "Respiratory Disease",
    "Pneumonia": "Respiratory Disease"
}


training top models

In [123]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    top_k_accuracy_score
)


In [80]:
models = {
    "svm": SVC(kernel="linear", probability=True),
    "RandomForestClassifier": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    "GradientBoostingClassifier": GradientBoostingClassifier(
        n_estimators=100,
        random_state=42,
    )
}

labels = np.unique(y_train)


for model_name, model in models.items():

    print("\n" + "="*60)
    print(f"Training model: {model_name}")

    # Train
    model.fit(x_train, y_train)

    # Predictions
    y_pred = model.predict(x_test)

    # Top-1 Accuracy
    acc = accuracy_score(y_test, y_pred)
    print(f"Top-1 Accuracy for {model_name}: {acc:.4f}")

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {model_name}:\n{cm}")

    # Classification Report
    print(f"Classification Report for {model_name}:")
    print(classification_report(y_test, y_pred))

    # Top-3 Accuracy
    probs = model.predict_proba(x_test)

    top3_acc = top_k_accuracy_score(
        y_test,
        probs,
        k=3,

       labels=labels
    )

    print(f"Top-3 Accuracy for {model_name}: {top3_acc:.4f}")


Training model: svm
Top-1 Accuracy for svm: 0.9380
Confusion Matrix for svm:
[[23  0  0 ...  0  0  0]
 [ 0 20  0 ...  0  0  0]
 [ 0  0 20 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 24  0]
 [ 0  0  0 ...  0  0 24]]
Classification Report for svm:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92        24
           1       0.91      0.83      0.87        24
           2       0.91      0.83      0.87        24
           3       0.96      1.00      0.98        24
           4       0.88      0.96      0.92        24
           5       0.88      0.92      0.90        24
           6       0.88      0.96      0.92        24
           7       0.89      1.00      0.94        24
           8       0.96      1.00      0.98        24
           9       0.86      0.79      0.83        24
          10       1.00      1.00      1.00        24
          11       1.00      1.00      1.00        24
          12       0.96      1.0

In [107]:
import os
import pickle

os.makedirs("models", exist_ok=True)  # creates folder if not present

with open("models/svc1.pkl", "wb") as f:
    pickle.dump(svc, f)
print("✅ svc1.pkl saved successfully")

✅ svc1.pkl saved successfully


single predictions

In [108]:
svc=pickle.load(open("models/svc1.pkl","rb"))

In [109]:
import os
print(os.path.exists("models/svc1.pkl"))
print(os.listdir("models"))


True
['svc1.pkl']


In [85]:
print(
    "predicted label:",
    svc.predict(x_test[0].reshape(1, -1))
)

print("actual label:", y_test[0])


predicted label: [23]
actual label: 15


recommendation system and prediction


In [86]:
sysm_df=pd.read_csv("/content/symtoms_df.csv",on_bad_lines="skip")
precautions_df=pd.read_csv("/content/precautions_df.csv",on_bad_lines="skip")
workout_df=pd.read_csv("/content/workout_df.csv",on_bad_lines="skip")
description_df=pd.read_csv("/content/description.csv",on_bad_lines="skip")
medications_df=pd.read_csv("/content/medications.csv",on_bad_lines="skip")
diets_df=pd.read_csv("/content/diets.csv",on_bad_lines="skip")
train_df = pd.read_csv("/content/Training.csv",on_bad_lines="skip")


In [127]:
import pickle
import numpy as np

with open("/content/models/svc1.pkl", "rb") as f:
    svc = pickle.load(f)

with open("/content/models/symptoms_list.pkl", "rb") as f:
    symptoms_list = pickle.load(f)

with open("/content/models/disease_dict.pkl", "rb") as f:
    disease_dict = pickle.load(f)



In [101]:
print(len(symptoms_list))        # must be 132
print(svc.n_features_in_)        # must be 132


132
132


In [57]:

#symptoms_list = {'itching': 0, 'skin rash': 1, 'nodal skin eruptions': 2, 'continuous sneezing': 3, 'shivering': 4, 'chills': 5, 'joint pain': 6, 'stomach pain': 7, 'acidity': 8, 'ulcers on tongue': 9, 'muscle wasting': 10, 'vomiting': 11, 'burning micturition': 12, 'spotting urination': 13, 'fatigue': 14, 'weight gain': 15, 'anxiety': 16, 'cold hands and feets': 17, 'mood swings': 18, 'weight loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches in throat': 22, 'irregular sugar level': 23, 'cough': 24, 'high fever': 25, 'sunken eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish skin': 32, 'dark urine': 33, 'nausea': 34, 'loss of appetite': 35, 'pain behind the eyes': 36, 'back pain': 37, 'constipation': 38, 'abdominal pain': 39, 'diarrhoea': 40, 'mild fever': 41, 'yellow urine': 42, 'yellowing of eyes': 43, 'acute liver failure': 44, 'fluid overload': 45, 'swelling of stomach': 46, 'swelled lymph nodes': 47, 'malaise': 48, 'blurred and distorted vision': 49, 'phlegm': 50, 'throat irritation': 51, 'redness of eyes': 52, 'sinus pressure': 53, 'runny nose': 54, 'congestion': 55, 'chest pain': 56, 'weakness in limbs': 57, 'fast heart rate': 58, 'pain during bowel movements': 59, 'pain in anal region': 60, 'bloody stool': 61, 'irritation in anus': 62, 'neck pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen legs': 68, 'swollen blood vessels': 69, 'puffy face and eyes': 70, 'enlarged thyroid': 71, 'brittle nails': 72, 'swollen extremeties': 73, 'excessive hunger': 74, 'extra marital contacts': 75, 'drying and tingling lips': 76, 'slurred speech': 77, 'knee pain': 78, 'hip joint pain': 79, 'muscle weakness': 80, 'stiff neck': 81, 'swelling joints': 82, 'movement stiffness': 83, 'spinning movements': 84, 'loss of balance': 85, 'unsteadiness': 86, 'weakness of one body side': 87, 'loss of smell': 88, 'bladder discomfort': 89, 'foul smell of urine': 90, 'continuous feel of urine': 91, 'passage of gases': 92, 'internal itching': 93}


In [58]:
d#isease_dict={0: 'Fungal infection', 1: 'Allergy', 2: 'GERD', 3: 'Chronic cholestasis', 4: 'Drug Reaction', 5: 'Peptic ulcer diseae', 6: 'AIDS', 7: 'Diabetes ', 8: 'Gastroenteritis', 9: 'Bronchial Asthma', 10: 'Hypertension ', 11: 'Migraine', 12: 'Cervical spondylosis', 13: 'Paralysis (brain hemorrhage)', 14: 'Jaundice', 15: 'Malaria', 16: 'Chicken pox', 17: 'Dengue', 18: 'Typhoid', 19: 'hepatitis A', 20: 'Hepatitis B', 21: 'Hepatitis C', 22: 'Hepatitis D', 23: 'Hepatitis E', 24: 'Alcoholic hepatitis', 25: 'Tuberculosis', 26: 'Common Cold', 27: 'Pneumonia', 28: 'Dimorphic hemmorhoids(piles)', 29: 'Heart attack', 30: 'Varicose veins', 31: 'Hypothyroidism', 32: 'Hyperthyroidism', 33: 'Hypoglycemia', 34: 'Osteoarthristis', 35: 'Arthritis', 36: '(vertigo) Paroymsal  Positional Vertigo', 37: 'Acne', 38: 'Urinary tract infection', 39: 'Psoriasis', 40: 'Impetigo'}



In [128]:
def normalize_symptom(symptom):
    return symptom.strip().lower().replace(" ", "_")


In [129]:
import ast

def helper(dis):
    # =======================
    # Description
    # =======================
    desc = description_df[description_df['Disease'] == dis]['Description']
    desc = " ".join(desc.values)

    # =======================
    # Precautions (FIXED)
    # =======================
    pre_df = precautions_df[precautions_df['Disease'] == dis][
        ['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']
    ]

    precautions = []
    if not pre_df.empty:
        precautions = pre_df.iloc[0].dropna().tolist()

    # =======================
    # Medications
    # =======================
    med_series = medications_df[medications_df['Disease'] == dis]['Medication']
    medications = []
    for row in med_series.values:
        medications.extend(ast.literal_eval(row))

    # =======================
    # Diet
    # =======================
    diet_series = diets_df[diets_df['Disease'] == dis]['Diet']
    diet = []
    for row in diet_series.values:
        diet.extend(ast.literal_eval(row))

    # =======================
    # Workout
    # =======================
    wrkout = workout_df[workout_df['disease'] == dis]['workout']
    workout = wrkout.values.tolist()

    return desc, precautions, medications, diet, workout





In [130]:
def get_top_3_predictions(patient_symptoms, top_k=3):
    input_vector = np.zeros(len(symptoms_list))
    valid_found = False

    for symptom in patient_symptoms:
        symptom = normalize_symptom(symptom)

        if symptom in symptoms_list:
            idx = symptoms_list.index(symptom)
            input_vector[idx] = 1
            valid_found = True
        else:
            print(f"⚠️ Unknown symptom ignored: {symptom}")

    if not valid_found:
        return {
            "error": "No valid symptoms detected. Please enter symptoms from the known list."
        }

    probs = svc.predict_proba([input_vector])[0]
    top_indices = np.argsort(probs)[-top_k:][::-1]

    results = []
    for idx in top_indices:
        disease = disease_dict[idx]
        confidence = round(probs[idx] * 100, 2)

        desc, pre, med, diet, wrk = helper(disease)

        results.append({
            "disease": disease,
            "confidence": confidence,
            "description": desc,
            "precautions": pre,
            "medications": med,
            "diet": diet,
            "workout": wrk
        })

    return results

In [131]:
symptoms = input("Enter the symptoms: ")

user_symptoms = [
    s.strip().lower().replace("_", " ")
    for s in symptoms.split(",")
]

top_results = get_top_3_predictions(user_symptoms)

print("\n================ TOP 3 PREDICTIONS ================\n")

if not top_results:
    print("❌ No valid symptoms detected.")
else:
    for i, res in enumerate(top_results, start=1):

        print(f"\n#{i} Disease: {res['disease']} ({res['confidence']}%)")

        if res["confidence"] < 50:
            print("⚠️ Low confidence prediction. Please consult a medical professional.")

        print("\nDescription:")
        print(res["description"])

        print("\nPrecautions:")
        for p in res["precautions"]:
            print("-", p)

        print("\nMedications:")
        for m in res["medications"]:
            print("-", m)

        print("\nWorkout:")
        for w in res["workout"]:
            print("-", w)

        print("\nDiet:")
        for d in res["diet"]:
            print("-", d)

        print("\n" + "-" * 60)


Enter the symptoms: excessive hunger,drying and tingling lips

================ TOP 3 PREDICTIONS ================


#1 Disease: Fungal infection (7.22%)
⚠️ Low confidence prediction. Please consult a medical professional.

Description:
Fungal infection is a common skin condition caused by fungi.

Precautions:
- bath twice
- use detol or neem in bathing water
- keep infected area dry
- use clean cloths

Medications:
- Antifungal Cream
- Fluconazole
- Terbinafine
- Clotrimazole
- Ketoconazole

Workout:
- Avoid sugary foods
- Consume probiotics
- Increase intake of garlic
- Include yogurt in diet
- Limit processed foods
- Stay hydrated
- Consume green tea
- Eat foods rich in zinc
- Include turmeric in diet
- Eat fruits and vegetables

Diet:
- Antifungal Diet
- Probiotics
- Garlic
- Coconut oil
- Turmeric

------------------------------------------------------------

#2 Disease: Heart attack (7.1%)
⚠️ Low confidence prediction. Please consult a medical professional.

Description:
Heart at

In [ ]:
Dimport sklearn
print(sklearn.__version__)

In [104]:
!mkdir medication-recommendation-system


In [135]:
!rm -rf medication-recommendation-system


In [106]:
# delete old models folder inside repo
!rm -rf medication-recommendation-system/models

In [136]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [137]:
%cd /content


/content


In [138]:
!ls -a


.		 diets.csv	     precautions_df.csv    Training.csv
..		 .ipynb_checkpoints  sample_data	   workout_df.csv
.config		 medications.csv     Symptom-severity.csv
description.csv  models		     symtoms_df.csv


In [139]:
%cd /content

/content


In [140]:
!git init


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [141]:
!git branch -m main


In [142]:
!git remote add origin https://github.com/jiakhelal/medication-recommendation-system-.git


In [143]:
!git remote -v


origin	https://github.com/jiakhelal/medication-recommendation-system-.git (fetch)
origin	https://github.com/jiakhelal/medication-recommendation-system-.git (push)


In [144]:
!ls


description.csv  models		     Symptom-severity.csv  workout_df.csv
diets.csv	 precautions_df.csv  symtoms_df.csv
medications.csv  sample_data	     Training.csv


In [146]:
!pwd
!ls -a


/content
.		 diets.csv	     models		   symtoms_df.csv
..		 .git		     precautions_df.csv    Training.csv
.config		 .ipynb_checkpoints  sample_data	   workout_df.csv
description.csv  medications.csv     Symptom-severity.csv


In [148]:
!git remote add origin https://github.com/jiakhelal/medication-recommendation-system-.git


error: remote origin already exists.


In [149]:
!git status
!git add models medication_recommendation_system.ipynb
!git commit -m "Update models and notebook"
!git branch -M main
!git push -u origin main


On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	Symptom-severity.csv
	Training.csv
	description.csv
	diets.csv
	medications.csv
	models/
	precautions_df.csv
	sample_data/
	symtoms_df.csv
	workout_df.csv

nothing added to commit but untracked files present (use "git add" to track)
fatal: pathspec 'medication_recommendation_system.ipynb' did not match any files
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@75e21a8e5019.(none)')
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/jiakhelal/medication-recommendation-system-.git'


In [150]:
!git config --global user.name "jiakhelal"
!git config --global user.email "jiakhelal15@gmail.com"


In [151]:
!git config --global --list


user.name=jiakhelal
user.email=jiakhelal15@gmail.com


In [152]:
!ls


description.csv  models		     Symptom-severity.csv  workout_df.csv
diets.csv	 precautions_df.csv  symtoms_df.csv
medications.csv  sample_data	     Training.csv
